module.exports = exports = [
	{
		id: 11,
		client: "Avvio",
		name: "Wordsearch Game",
		description: "A wordsearch game",
		tags: ["Wordsearch", "Game", "Avvio", "Avvio Reply", "Handlebars", "Popups"],
		notes: [],
		contentFolder: "avvio wordsearch",
		noImages: 3,
		playableLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html",
		githubLink: "https://github.com/ryandixon555/avvio-wordsearch/tree/master"
	},
	{
		id: 10,
		client: "Avvio",
		name: "Christmas Movie Challenge",
		description: "A quiz game where you have to guess the movies title by the image.",
		tags: ["Quiz","Game", "Avvio", "Avvio Reply"],
		notes: [],
		contentFolder: "Avvio Movie Challenge",
		noImages: 3,
		playableLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html",
		githubLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html"
	},
	{
		id: 9,
		client: "Avvio",
		name: "Avvio Digital Puzzle",
		description: "A 9-square puzzle against the clock. Match the pattern on the side to be in for a chance to win a prize.",
		tags: ["Puzzle","Game", "Avvio", "Avvio Reply"],
		notes: [],
		contentFolder: "Avvio Digital Puzzle",
		noImages: 3,
		playableLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html",
		githubLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html"
	},
	{
		id: 8,
		client: "Avvio",
		name: "Superhero Name Generator",
		description: "A very simple superhero name generator.",
		tags: ["Generator","Game", "Avvio", "Avvio Reply"],
		notes: [],
		contentFolder: "Avvio Superhero Name Generator",
		noImages: 5,
		playableLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html",
		githubLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html"
	},
	{
		id: 7,
		client: "Avvio",
		name: "Wheel of Fortune",
		description: "A Wheel of Fortune that employees to earn points. They had 3 spins to earn as many points as possible to win prizes.",
		tags: ["Game", "Avvio", "Avvio Reply", "Gambling"],
		notes: [],
		contentFolder: "Avvio Wheel of Fortune",
		noImages: 5,
		playableLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html",
		githubLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html"
	},
	{
		id: 6,
		client: "Avvio",
		name: "Drag And Drop Game",
		description: "A drag and drop game – match the ‘perfect partnership’ pairs.",
		tags: ["Drag and drop", "Matching","Game", "Avvio", "Avvio Reply"],
		notes: [],
		contentFolder: "avvio drag and drop game",
		noImages: 4,
		playableLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html",
		githubLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html"
	},
	{
		id: 4,
		client: "Avvio",
		name: "Wher'es Wally",
		description: "A ‘Where’s Wally’ style game – find and click on the 15 hidden Easter eggs in the illustration to reveal some of the benefits they have at Sky.",
		tags: ["Finder", "Illustration","Game", "Avvio", "Avvio Reply"],
		notes: [],
		contentFolder: "avvio wheres wally",
		noImages: 3,
		playableLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html",
		githubLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html"
	},
	{
		id: 3,
		client: "Avvio",
		name: "Avvio Claw",
		description: "A timed reaction speed game – the digital grabber moves left to right, when it looks aligned with one of the icons you need to click the GRAB button to collect it.",
		tags: ["Claw grabber", "Innovation Month", "Timed", "Game", "Avvio", "Avvio Reply",],
		notes: [],
		contentFolder: "avvio claw",
		noImages: 5,
		playableLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html",
		githubLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html"
	},
	{
		id: 2,
		client: "Avvio",
		name: "Space Raiders",
		description: "A timed reaction speed game – the graphic at the bottom moves from left to right, when it looks aligned with one of the barrier rows you need to click the button to ZAP them. The aim is to zap all the barriers and release the 6 icons at the top.",
		tags: ["Space Invaders", "Innovation Month", "Timed", "Game", "Avvio", "Avvio Reply",],
		notes: [],
		contentFolder: "avvio space raiders",
		noImages: 6,
		playableLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html",
		githubLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html"
	},
	{
		id: 1,
		client: "Avvio",
		name: "Snake",
		description: "A snake style game where you use the arrows to move the ‘snake’ around the board and catch the icons that pop up.",
		tags: ["Snake", "Innovation Month", "Game", "Avvio", "Avvio Reply",],
		notes: [],
		contentFolder: "avvio snake",
		noImages: 5,
		playableLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html",
		githubLink: "https://ryandixon555.github.io/avvio-wordsearch/public/index.html"
	}
];